webpack outside cache

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -41,27 +41,29 @@ jobs:
       - name: cache node_modules
         uses: actions/cache@v3
         with:
-          path: |
-            "**/.yarn/cache"
-            "**/.yarn/unplugged"
+          path: ".yarn"
           key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
 
       - name: cache webpack modules
         uses: actions/cache@v3
         with:
-          path: "**/.yarn/.cache"
+          path: ".cache"
           key: ${{ runner.os }}-webpack-${{ github.run_id }}
           restore-keys: |
             ${{ runner.os }}-webpack
 
-      - name: show webpack cache
-        run: ls -lR .yarn/.cache || true
-
       - name: Install deps
         run: yarn install --immutable
+
+      - name: Move back Webpack cache
+
+        run: \[ -d ".cache" \] &&  mv .cache .yarn/.cache || echo "cache not found."
 
       - name: show cache
         run: ls -l .yarn || true
 
       - name: Build project
-        run: yarn build
+        run: yarn build --no-minify
+
+      - name: Move Webpack cache
+        run: mv .yarn/.cache .cache
